import type { Metadata } from 'next'
import { Quicksand } from "next/font/google"
import './globals.css'
import { cn } from "@/lib/utils"
import Provider from './Provider'
import Navbar from './Navbar'


export const fontSans = Quicksand({
  subsets: ["vietnamese"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'Smart wash',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}      >
        <Provider>
          <div className='h-screen flex flex-col'>
            <Navbar />
            <div className='overflow-auto' style={{ height: 'calc(100vh - 72px)' }}>
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  )
}
